import { useEffect, useRef, useState } from 'react'
import { drawBrandQRCode } from './BrandQRCode.jsx'
import { uploadImage } from '../utils/uploadImage.js'
import { supabase } from '../supabaseClient.js'

function hexToRgb(hex) { const h = String(hex || '').replace('#',''); if (h.length !== 6) return [40,30,20]; return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)] }
function mix(a,b,n) { return a.map((v,i)=>Math.round(v+(b[i]-v)*n)) }
function rgb(a) { return `rgb(${a.join(',')})` }
function rounded(ctx,x,y,w,h,r){const q=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+q,y);ctx.arcTo(x+w,y,x+w,y+h,q);ctx.arcTo(x+w,y+h,x,y+h,q);ctx.arcTo(x,y+h,x,y,q);ctx.arcTo(x,y,x+w,y,q);ctx.closePath()}
function loadImage(url){if(!url)return Promise.resolve(null);return new Promise(resolve=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src=url})}
function drawCharacter(ctx,x,y,s,palette,logo,custom){
  if(custom){ctx.drawImage(custom,x,y,s,s);return}
  const [r,g,b]=hexToRgb(palette.primary); const primary=rgb([r,g,b]); const dark=rgb(mix([r,g,b],[20,14,10],.58)); const light=rgb(mix([r,g,b],[255,255,255],.62)); const skin='#f3c9a8'
  ctx.fillStyle=dark; rounded(ctx,x+s*.36,y+s*.76,s*.1,s*.22,s*.035);ctx.fill();rounded(ctx,x+s*.55,y+s*.76,s*.1,s*.22,s*.035);ctx.fill();ctx.fillStyle='#17120e';rounded(ctx,x+s*.31,y+s*.94,s*.17,s*.055,s*.025);ctx.fill();rounded(ctx,x+s*.52,y+s*.94,s*.17,s*.055,s*.025);ctx.fill();ctx.fillStyle=primary;rounded(ctx,x+s*.24,y+s*.43,s*.53,s*.37,s*.12);ctx.fill();ctx.fillStyle=light;rounded(ctx,x+s*.39,y+s*.44,s*.23,s*.32,s*.04);ctx.fill();ctx.fillStyle=skin;rounded(ctx,x+s*.13,y+s*.48,s*.15,s*.27,s*.07);ctx.fill();rounded(ctx,x+s*.70,y+s*.48,s*.15,s*.27,s*.07);ctx.fill();ctx.beginPath();ctx.arc(x+s*.5,y+s*.31,s*.19,0,Math.PI*2);ctx.fill();ctx.fillStyle='#231a14';ctx.beginPath();ctx.arc(x+s*.5,y+s*.25,s*.19,Math.PI,Math.PI*2);ctx.fill();ctx.fillStyle='#201914';ctx.beginPath();ctx.arc(x+s*.44,y+s*.31,s*.018,0,Math.PI*2);ctx.arc(x+s*.56,y+s*.31,s*.018,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#201914';ctx.lineWidth=s*.012;ctx.beginPath();ctx.arc(x+s*.5,y+s*.34,s*.06,.15,Math.PI-.15);ctx.stroke();ctx.fillStyle=primary;rounded(ctx,x+s*.28,y+s*.10,s*.44,s*.12,s*.035);ctx.fill();ctx.beginPath();ctx.ellipse(x+s*.5,y+s*.19,s*.27,s*.06,0,0,Math.PI*2);ctx.fill();if(logo) {ctx.save();rounded(ctx,x+s*.455,y+s*.112,s*.09,s*.09,s*.02);ctx.clip();ctx.drawImage(logo,x+s*.455,y+s*.112,s*.09,s*.09);ctx.restore()}
}
async function drawCard(canvas, { side, restaurantName, logoUrl, theme, qrUrl, characterUrl }) {
  const ctx=canvas.getContext('2d'); const W=1800,H=1080; canvas.width=W;canvas.height=H;ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';const t=theme||{};const primary=t.primary||'#c48a25',accent=t.accent||primary,soft=t.brandSoft||'#f5ead5',ink=t.ink||'#2b2018',paper=t.surface||'#fffaf2';const logo=await loadImage(logoUrl);const character=await loadImage(characterUrl)
  ctx.fillStyle=paper;ctx.fillRect(0,0,W,H);ctx.fillStyle=primary;rounded(ctx,0,0,W,H,64);ctx.fill();ctx.fillStyle=paper;rounded(ctx,22,22,W-44,H-44,48);ctx.fill()
  if(side==='front'){
    ctx.fillStyle=primary;rounded(ctx,48,48,W-96,210,42);ctx.fill();ctx.fillStyle=t.primaryText||'#fff';ctx.textAlign='left';ctx.textBaseline='middle';ctx.font='900 64px Inter,system-ui,sans-serif';ctx.fillText(restaurantName||'Restaurant',92,132);ctx.font='700 28px Inter,system-ui,sans-serif';ctx.fillText('HOME DELIVERY • ORDER ONLINE',92,190);if(logo){ctx.save();rounded(ctx,W-230,78,128,128,20);ctx.clip();ctx.drawImage(logo,W-230,78,128,128);ctx.restore()}
    drawCharacter(ctx,95,270,520,{primary},logo,character);ctx.fillStyle=soft;rounded(ctx,650,315,1030,620,50);ctx.fill();ctx.fillStyle=ink;ctx.textAlign='center';ctx.font='900 48px Inter,system-ui,sans-serif';ctx.fillText('Scan QR for home delivery',1165,390);ctx.font='600 25px Inter,system-ui,sans-serif';ctx.fillStyle=t.textMuted||'#6b6357';ctx.fillText('Choose your area and order online',1165,435);await drawBrandQRCode(ctx,qrUrl,850,470,390,t,logoUrl);ctx.fillStyle=accent;rounded(ctx,1290,575,300,165,28);ctx.fill();ctx.fillStyle=t.primaryText||'#fff';ctx.font='800 28px Inter,system-ui,sans-serif';ctx.fillText('ORDER • EAT • ENJOY',1440,650);ctx.font='600 21px Inter,system-ui,sans-serif';ctx.fillText('Fast ordering, same great taste.',1440,700)
  }else{ctx.fillStyle=soft;rounded(ctx,72,72,W-144,H-144,48);if(logo){ctx.save();rounded(ctx,W/2-80,135,160,160,24);ctx.clip();ctx.drawImage(logo,W/2-80,135,160,160);ctx.restore()}ctx.fillStyle=ink;ctx.textAlign='center';ctx.font='900 86px Georgia,serif';ctx.fillText('Thank you!',W/2,390);ctx.font='600 34px Inter,system-ui,sans-serif';ctx.fillStyle=t.textSecondary||ink;ctx.fillText('We hope to see you again soon.',W/2,470);ctx.font='700 28px Inter,system-ui,sans-serif';ctx.fillText('Scan the QR on the front for home delivery.',W/2,650)}
}

export default function BrandThankYouCard({ sessionId, restaurantName, logoUrl, theme={}, qrUrl }) {
  const frontRef=useRef(null),backRef=useRef(null),fileRef=useRef(null);const [busy,setBusy]=useState(true),[error,setError]=useState('');const characterUrl=theme?.thankYouCard?.characterUrl||''
  const draw=()=>{setBusy(true);setError('');Promise.all([drawCard(frontRef.current,{side:'front',restaurantName,logoUrl,theme,qrUrl,characterUrl}),drawCard(backRef.current,{side:'back',restaurantName,logoUrl,theme,qrUrl,characterUrl})]).catch(()=>setError('Card preview generate nahi ho saka.')).finally(()=>setBusy(false))}
  useEffect(()=>{draw()},[restaurantName,logoUrl,theme,qrUrl,characterUrl])
  const uploadCharacter=async(file)=>{if(!file)return;setBusy(true);try{const ext=(file.name.split('.').pop()||'png').toLowerCase();const path=`${sessionId}/thankyou-character-${Date.now()}.${ext}`;const url=await uploadImage('restaurant-logos',path,file);const next={...(theme||{}),thankYouCard:{...(theme?.thankYouCard||{}),characterUrl:url}};const {error:err}=await supabase.from('sessions').update({theme:next}).eq('id',sessionId);if(err)throw err;alert('Cartoon/character image saved.');window.location.reload()}catch(e){setError(e?.message||'Character upload failed.')}finally{setBusy(false)}}
  const download=(ref,name)=>{if(!ref.current||busy)return;const a=document.createElement('a');a.download=name;a.href=ref.current.toDataURL('image/png');a.click()}
  const print=()=>{if(!frontRef.current||!backRef.current||busy)return;const w=window.open('', '_blank','noopener,noreferrer,width=900,height=700');if(!w)return;const f=frontRef.current.toDataURL('image/png'),b=backRef.current.toDataURL('image/png');w.document.write(`<html><head><title>${restaurantName||'Thank You Card'}</title><style>body{margin:0;padding:20px;font-family:Arial;background:#fff}.page{width:90mm;height:54mm;object-fit:contain;display:block;margin:10mm auto;page-break-after:always}@page{size:A4;margin:10mm}</style></head><body><img class="page" src="${f}"><img class="page" src="${b}"></body></html>`);w.document.close();setTimeout(()=>{w.focus();w.print()},300)}
  return <div style={{display:'grid',gap:12}}><div style={{padding:12,borderRadius:16,background:'var(--brand-soft)',border:'1px solid var(--border)'}}><b>Physical Thank-You Card</b><div style={{fontSize:12,color:'var(--text-muted)',marginTop:4}}>Customer portal mein card show nahi hota. Counter se character upload/edit karein, phir print karein.</div></div>{error&&<div style={{color:'var(--clay)',fontSize:12}}>{error}</div>}<div style={{display:'grid',gap:12}}><canvas ref={frontRef} style={{width:'100%',height:'auto',display:'block',borderRadius:12}}/><canvas ref={backRef} style={{width:'100%',height:'auto',display:'block',borderRadius:12}}/></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button type="button" disabled={busy} onClick={()=>fileRef.current?.click()} style={btn}>Upload Cartoon / Character</button><button type="button" disabled={busy} onClick={()=>download(frontRef,'thank-you-front.png')} style={btn}>Download Front</button><button type="button" disabled={busy} onClick={()=>download(backRef,'thank-you-back.png')} style={btn}>Download Back</button><button type="button" disabled={busy} onClick={print} style={primaryBtn}>Print Card</button><input ref={fileRef} type="file" accept="image/*" onChange={e=>uploadCharacter(e.target.files?.[0])} style={{display:'none'}}/></div></div>
}
const btn={border:'1px solid var(--border)',borderRadius:10,padding:'10px 13px',background:'var(--surface)',color:'var(--ink)',fontWeight:800,fontSize:12};const primaryBtn={...btn,border:'none',background:'var(--brand-primary)',color:'var(--brand-primary-text)'}
